apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istiosystem
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
  - namespace: 'istio-system'
    server: 'https://kubernetes.default.svc'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'