apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
  destinations:
  - namespace: 'vault'
    server: 'https://kubernetes.default.svc'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'