apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphite
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: graphite
    repoURL: https://kiwigrid.github.io
    targetRevision: "1.1.0"
    helm:
      version: v3
      releaseName: secrets-store-csi-driver
      valuesObject:
        persistence:
          enabled: true
          storageClass: nfs-storage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  parameters:
    - name: "syncSecret.enabled"
      value: "true"
    - name: "enableSecretRotation"
      value: "true"
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
