apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: homeautomation
  source:
    chart: home-assistant
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    targetRevision: "0.2.78"
    helm:
      version: v3
      releaseName: home-assistant
      valuesObject:
        ingress:
          enabled: true
        configuration:
          enabled: true
        persistence:
          enabled: true
          storageClass: nfs-storage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-automation
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
