apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: homeautomation
  source:
    chart: home-assistant
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    targetRevision: "0.2.78"
    helm:
      version: v3
      releaseName: home-assistant
      valuesObject:
        configuration:
          enabled: true
          forceInit: true
          templateConfig: |-
            # Loads default set of integrations. Do not remove.
            default_config:
            http:
              use_x_forwarded_for: true
              trusted_proxies:
                {{- range .Values.configuration.trusted_proxies }}
                - {{ . }}
                {{- end }}
            # Load frontend themes from the themes folder
            frontend:
              themes: !include_dir_merge_named themes
        
            automation: !include automations.yaml
            script: !include scripts.yaml
            scene: !include scenes.yaml
        persistence:
          enabled: true
          storageClass: nfs-storage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-automation
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
