apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "58.2.2"
    helm:
      version: v3
      releaseName: prometheus-community
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: 
              any: true
            serviceMonitorSelector:
              matchLabels: {}
            storageSpec:
              volumeClaimTemplate:
                metadata:
                  name: prometheus-data
                spec:
                  storageClassName: "nfs-storage"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi 
        grafana:
          initChownData:
            enabled: false
          persistence:
            enabled: true
            storageClassName: "nfs-storage"
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
        prometheusOperator:
          tls:
            enabled: false
          admissionWebhooks:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
