apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: vault
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: "0.28.0"
    helm:
      releaseName: vault
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true