apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: vault
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: "0.28.0"
    helm:
      version: v3
      releaseName: vault
      parameters:
        - name: "csi.enabled"
          value: "true"
      valuesObject:
        server:
          ha:
            enabled: false
          ingress:
            enabled: false
          dataStorage:
            storageClass: nfs-storage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
